json-smart is now on the classpath (because the UPN link rewriter uses non-trivial JSONPath filters), but not its dependencies, so the NoClassDefFoundError that occurs before Jackson is configured is different than before.